package com.mathkidsquiz.model;

import java.io.Serializable;

/**
 *
 * @author User
 */
public class User implements Serializable { // Implement Serializable for session storage
    private static final long serialVersionUID = 1L; // For Serializable
    private int id;
    private String username;
    private String password; //hashed password from database
    private String email;
    private String role;
    
    // Default constructor (no-argument constructor)
    public User() {
    }

    // Constructor for creating a new user (ID is auto-generated by DB)
    public User(String username, String password, String email, String role) {
        this.username = username;
        this.password = password;
        this.email = email;
        this.role = role;
    }

    // Constructor for retrieving user from database (ID is already known)
    public User(int id, String username, String password, String email, String role) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.email = email;
        this.role = role;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }
    
    @Override
    public String toString() {
        return "User{" +
               "id=" + id +
               ", username='" + username + '\'' +
               ", email='" + email + '\'' +
               ", role='" + role + '\'' +
               '}';
    }
}
